# Jekyll configuration

# Site settings
title: B. L. Alterman
baseurl: ""
url: ""
ads_orcid: "0000-0001-6673-3432"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Build settings
markdown: kramdown
