# Jekyll configuration

# Site settings
title: B. L. Alterman
logo: "/assets/images/headshot.jpg"
baseurl: ""
url: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Build settings
markdown: kramdown
